using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UpdateControls;
namespace DMC_Robot_Editor.Classes
{
    /// <summary>
    /// Stores all application-level data, including the currently
    /// open file and the list of recently opened files.
    /// </summary>
    public class ApplicationDataModel
    {
        private string _lastAction;
        private string _openFileName;
        private List<string> _recentFiles = new List<string>();

        #region Independent properties
        // Generated by Update Controls --------------------------------
        private Independent _indLastAction = new Independent();
        private Independent _indOpenFileName = new Independent();
        private Independent _indRecentFiles = new Independent();

        public string LastAction
        {
            get { _indLastAction.OnGet(); return _lastAction; }
            set { _indLastAction.OnSet(); _lastAction = value; }
        }

        public string OpenFileName
        {
            get { _indOpenFileName.OnGet(); return _openFileName; }
        }

        public IEnumerable<string> RecentFiles
        {
            get { _indRecentFiles.OnGet(); return _recentFiles; }
        }
        // End generated code --------------------------------
        #endregion

        public void OpenFile(string fileName)
        {
            // Set the currently open file.
            _indOpenFileName.OnSet();
            _openFileName = fileName;

            // Remove it from the list of most recent files, if it's there.
            _indRecentFiles.OnSet();
            _recentFiles.Remove(fileName);

            // Add to the list of most recent files.
            _recentFiles.Insert(0, fileName);

            // Keep only the most recent 5 files.
            if (_recentFiles.Count > 5)
                _recentFiles = _recentFiles.GetRange(0, 5);
        }

        public void CloseFile()
        {
            // Clear the currently open file.
            _indOpenFileName.OnSet();
            _openFileName = null;
        }
    }
}
