//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miRobotEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("miRobotEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}ms to parse shift.
        /// </summary>
        public static string AbstractRobotClass_ShiftProgram__0_ms_to_parse_shift {
            get {
                return ResourceManager.GetString("AbstractRobotClass_ShiftProgram__0_ms_to_parse_shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of {0} requires .Net 4.0. Your are using:{1}.
        /// </summary>
        public static string CheckEnvironment {
            get {
                return ResourceManager.GetString("CheckEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All _files (*.*)|*.*|ABB _files (.mod,.prg,.cfg)|*.mod;*.prg;*.cfg|Kawasaki _files(*.as)|*.as|KUKA _files (.sub,.src,.dat,.kfd)|*.sub;*.src;*.dat;*.kfd|Fanuc _files (*.ls)|*.ls.
        /// </summary>
        public static string DefaultFilter {
            get {
                return ResourceManager.GetString("DefaultFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sites.google.com/site/dmcautomation/home/software/dmc-robot-editor.
        /// </summary>
        public static string DownloadsPage {
            get {
                return ResourceManager.GetString("DownloadsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon editor {
            get {
                object obj = ResourceManager.GetObject("editor", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find _All.
        /// </summary>
        public static string FindAll {
            get {
                return ResourceManager.GetString("FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find _Next.
        /// </summary>
        public static string FindNext {
            get {
                return ResourceManager.GetString("FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find _Previous.
        /// </summary>
        public static string FindPrevious {
            get {
                return ResourceManager.GetString("FindPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find What:.
        /// </summary>
        public static string FindWhat {
            get {
                return ResourceManager.GetString("FindWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Line Number (1-{0}):.
        /// </summary>
        public static string GotoDialog_GotoDialog_OnLoaded_Enter_Line_Number__1__0___ {
            get {
                return ResourceManager.GetString("GotoDialog_GotoDialog_OnLoaded_Enter_Line_Number__1__0___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KUKA vxWorks File (*.rt)|*.rt.
        /// </summary>
        public static string KUKA_SystemFileName_KUKA_VxWorks_File__vxWorks_rt_VxWorks_Debug__vxWorks_rt_vxWorks_debug {
            get {
                return ResourceManager.GetString("KUKA_SystemFileName_KUKA_VxWorks_File__vxWorks_rt_VxWorks_Debug__vxWorks_rt_vxWor" +
                        "ks_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        public static string MatchCase {
            get {
                return ResourceManager.GetString("MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match whole word.
        /// </summary>
        public static string MatchWholeWord {
            get {
                return ResourceManager.GetString("MatchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoMergeStyle can only used in Control.
        /// </summary>
        public static string MergeStyleBehaviour_OnAutoMergeStyleChanged_AutoMergeStyle_can_only_used_in_Control {
            get {
                return ResourceManager.GetString("MergeStyleBehaviour_OnAutoMergeStyleChanged_AutoMergeStyle_can_only_used_in_Contr" +
                        "ol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (null).
        /// </summary>
        public static string MergeStyleBehaviour_OnBaseOnStyleChanged__null_ {
            get {
                return ResourceManager.GetString("MergeStyleBehaviour_OnBaseOnStyleChanged__null_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseOnStyle can only be used in Control.
        /// </summary>
        public static string MergeStyleBehaviour_OnBaseOnStyleChanged_BaseOnStyle_can_only_be_used_in_Control {
            get {
                return ResourceManager.GetString("MergeStyleBehaviour_OnBaseOnStyleChanged_BaseOnStyle_can_only_be_used_in_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DependencyObject d: {0}.
        /// </summary>
        public static string MergeStyleBehaviour_OnBaseOnStyleChanged_DependencyObject_d___0_ {
            get {
                return ResourceManager.GetString("MergeStyleBehaviour_OnBaseOnStyleChanged_DependencyObject_d___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newStyle: {0}.
        /// </summary>
        public static string MergeStyleBehaviour_OnBaseOnStyleChanged_newStyle___0_ {
            get {
                return ResourceManager.GetString("MergeStyleBehaviour_OnBaseOnStyleChanged_newStyle___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap objectbrowser {
            get {
                object obj = ResourceManager.GetObject("objectbrowser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Replace.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace A_ll.
        /// </summary>
        public static string ReplaceAll {
            get {
                return ResourceManager.GetString("ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace With:.
        /// </summary>
        public static string ReplaceWith {
            get {
                return ResourceManager.GetString("ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Shifting Program. Progress:= {0}&quot;.
        /// </summary>
        public static string ShiftingProgram {
            get {
                return ResourceManager.GetString("ShiftingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Regular Expressions.
        /// </summary>
        public static string UseRegularExpressions {
            get {
                return ResourceManager.GetString("UseRegularExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.DMCEngineering.com.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
